<?php
$chip="3520D";
$type="ENC1H";
$rootPath="/root/usb";
$record=true;
$carousel=true;
$motionDetect=true;
$enableSub=true;
$DHCP=true;
$defLang="cn";
$maxENC=165888000;
$HDMI_Out=true;
$line=true;
$PortCtrl=true;
$help="120.78.2.184";
?>
